SandboxTemplate now needs to call super().init
presumably this is due to changes in troposphere and/or troposphere_sugar

The error was as follows:
make create-stack
env/bin/python cfn-sandbox.py sandbox.pilosa.com > cfn-sandbox.json
Traceback (most recent call last):
  File "cfn-sandbox.py", line 119, in <module>
    main()
  File "cfn-sandbox.py", line 116, in main
    print SandboxTemplate(domain=domain).output
  File "/Users/jaffee/go/src/github.com/pilosa/infrastructure/cfn-sandbox/env/lib/python2.7/site-packages/troposphere_sugar/skel.py", line 53, in output
    self.process()
  File "/Users/jaffee/go/src/github.com/pilosa/infrastructure/cfn-sandbox/env/lib/python2.7/site-packages/troposphere_sugar/skel.py", line 44, in process
    if not self._processed:
AttributeError: 'SandboxTemplate' object has no attribute '_processed'
make: *** [cfn-sandbox.json] Error 1